config_version: 1

# General settings.
general:
  # The codename of the device.
  device_codename:
  # The operating system name.
  os_name: cm
  # The operating system version.
  os_version: 11
  # The template name.
  template: mia-default

defaults:
  # The default repository for apps.
  repository: fdroid

app_types:
  system: system/app
  privileged: system/priv-app
  user: data/app

# A list of repositories for the F-Droid application.
repositories:
  - id: fdroid
    name: F-Droid
    url: https://f-droid.org/repo
    fallback: fdroid_archive
  - id: fdroid_archive
    name: F-Droid Archive
    url: https://f-droid.org/archive
  - id: guardian
    name: Guardian Project
    url: https://dev.guardianproject.info/fdroid/repo
    fallback: guardian_archive
  - id: guardian_archive
    name: Guardian Project Archive
    url: https://dev.guardianproject.info/fdroid/archive
    # Until a proper release in official F-Droid repo
  - id: orfox_devel
    name: Orfox Development
    url: https://dev.guardianproject.info/debug/info.guardianproject.orfox/fdroid/repo

# Apps from the main F-Droid repository.
apps:
  - id: org.fdroid.fdroid
    versioncode: 96150
    hash: 481f2f1ec4e0fd21279018d5fa6b31086fc4cdd4bb88c2a3d074a0db1df8d24c
    app_type: privileged
  - id: be.uhasselt.privacypolice
  - id: com.artifex.mupdfdemo
  - id: com.csipsimple
  - id: com.fsck.k9
  - id: com.morlunk.mumbleclient
  - id: com.projectsexception.myapplist.open
  - id: com.xabber.androiddev
  - id: de.schildbach.wallet
  - id: fr.kwiatkowski.ApkTrack
  - id: indrora.atomic
  - id: info.guardianproject.orfox
    repository: orfox_devel
  - id: jackpal.androidterm
  - id: net.osmand.plus
  - id: org.coolreader
  - id: org.ethack.orwall
  - id: org.mariotaku.twidere
  - id: org.mozilla.fennec_fdroid
  - id: org.nick.cryptfs.passwdmanager
  - id: org.sufficientlysecure.keychain
  - id: org.sufficientlysecure.localcalendar
  - id: org.torproject.android
    versioncode: 133
  - id: org.videolan.vlc
