
# General settings.
general:
  # The CyanogenMod codename of the device.
  cm_device_codename:
  # Preferred CyanogenMod release type
  cm_release_type: snapshot
  # Preferred CyanogenMod release version
  cm_release_version: M12

defaults:
  # The default repository for apps.
  repository_id: fdroid

# Mapping of the items in the definition and their place in the update archive.
update_content:
  - src: init.d
    dst: system/etc/init.d
  - src: META-INF
    dst: META-INF
  - src: misc
    dst: sdcard/misc
  - src: system-apps
    dst: system/priv-app
  - src: system-lib
    dst: system/lib
  - src: user-apps
    dst: data/app
  - src: user-data
    dst: data/data
  - src: other/update-binary
    dst: META-INF/com/google/android/update-binary
  - src: other/updater-script
    dst: META-INF/com/google/android/updater-script
  - src: other/firstboot.sh
    dst: data/.firstboot.sh

# A list of repositories for the F-Droid application.
repositories:
  - id: fdroid
    name: F-Droid
    url: https://f-droid.org/repo
    fallback: fdroid_archive
  - id: fdroid_archive
    name: F-Droid Archive
    url: https://f-droid.org/archive

# Apps from the main F-Droid repository.
apps:
  - name: org.fdroid.fdroid
    code: 830
    path: system-apps
  - name: info.guardianproject.orfox
    url: https://guardianproject.info/builds/OrfoxFennec/2014-08-22_23-32-22/OrfoxFennec-debug.apk
  - name: org.anhonesteffort.flock
    url: https://flock-supplychain.s3.amazonaws.com/apks/org.anhonesteffort.flock-4b93f078-cae6-4997-a1c2-ef833b2ac2c1.apk
  - name: com.artifex.mupdfdemo
    code: 55
  - name: com.csipsimple
    code: 2459
  - name: com.fsck.k9
    code: 22004
  - name: com.morlunk.mumbleclient
    code: 72
  - name: com.projectsexception.myapplist.open
    code: 16
  - name: com.xabber.androiddev
    code: 136
  - name: de.schildbach.wallet
    code: 211
  - name: fr.kwiatkowski.ApkTrack
    code: 4
  - name: indrora.atomic
    code: 19
  - name: net.osmand.plus
    code: 197
  - name: org.coolreader
    code: 875
  - name: org.ethack.orwall
    code: 36
  - name: org.mariotaku.twidere
    code: 98
  - name: org.mozilla.fennec_fdroid
    code: 370000
  - name: org.sufficientlysecure.keychain
    code: 31200
  - name: org.nick.cryptfs.passwdmanager
    code: 1230
  - name: org.sufficientlysecure.localcalendar
    code: 6
  - name: org.torproject.android
    code: 133
  - name: org.videolan.vlc
    code: 1020304
